name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.0", "1.24.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Build
        run: go build -v ./...
      - name: Test (no coverage) for older version
        if: matrix.go-version == '1.23.0'
        run: go test -v ./...
      - name: Test with coverage for newer version
        if: matrix.go-version == '1.24.x'
        run: go test -v -cover -coverprofile=coverage.txt ./...
      - name: Upload coverage reports to Codecov
        if: matrix.go-version == '1.24.x'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
